### PR TITLE
Disallow servers to exceed instance's max emoji limit by one

### LINKED ISSUE #295: bug: server emoji count can be 1 more than the set limit
### What happened?

As pointed out by [Toatrika#5321 on Revolt's Server](https://app.revolt.chat/server/01F7ZSBSFHQ8TA81725KQCSDDP/channel/01F92C5ZXBQWQ8KY7J8KY917NM/01HGS65T457V7N6XWM9HYG8R59), It seems like servers can have exactly one more emoji than the limit imposed by the server.

I checked the source code and found out that in [line 48 of customization/emoji_create.rs](https://github.com/revoltchat/backend/blob/25016efbc2bbe96fbe79f2dc1b29dee3c924007c/crates/delta/src/routes/customisation/emoji_create.rs#L48), the backend is checking if the server's emoji count is *greater than* the maximum limit, which means that a server can have 101 emotes.

## Proposed change (literally 2 characters that I am too lazy to change)

```diff
// ...

- if emojis.len() > config.features.limits.default.server_emoji {
+ if emojis.len() >= config.features.limits.default.server_emoji {
                return Err(create_error!(TooManyEmoji {
                    max: config.features.limits.default.server_emoji,
                }));
            }

// ...
```

### PR DESCRIPTION
**Pull request by amycatgirl**
funny message goes here

closes #295 

## Please make sure to check the following tasks before opening and submitting a PR

* [x] I understand and have followed the [contribution guide](https://github.com/revoltchat/revolt/discussions/282)
* [x] I have tested my changes locally and they are working as intended
* [x] These changes do not have any notable side effects on other Revolt projects

### CODE REVIEW

**Comment by amycatgirl** [comment]
I have read the CLA Document and I hereby sign the CLA

**Comment by amycatgirl** [comment]
recheck

**Review by sussycatgirl — APPROVED** [review]
lgtm

**Comment by amycatgirl** [comment]
absolutely nothing has changed
but github is being stinky and won't let me merge the PR after the branch rulesets changed even though @sussycatgirl reviewed it 🥺

**Review by insertish — APPROVED** [review]

**Pull request merged**
