### PR TITLE
replace runtime image to distrolles run as noroot

### PR DESCRIPTION
**Pull request by MaticPoh**
I've implemented distrolles to remove CVEs from libraries not used in the project, you never know when they might haunt you hahaha

https://github.com/revoltchat/backend/issues/298

https://github.com/revoltchat/backend/security/advisories/GHSA-m2p9-rmqf-455p

### Please make sure to check the following tasks before opening and submitting a PR

- [X] I understand and have followed the https://github.com/revoltchat/revolt/discussions/282
- [X] I have tested my changes locally and they are working as intended
- [X] These changes do not have any notable side effects on other Revolt projects

### CODE REVIEW

**Comment by Rexogamer** [comment]
Just realised that this is held on the CLA being signed - once done, we should be able to review this

**Comment by MaticPoh** [comment]
I have read the CLA Document and I hereby sign the CLA

**Comment by Rexogamer** [comment]
(the CLA has since been removed; ready for review in any case)

**Comment by insertish** [comment]
Need to make sure everything still runs properly with the environment change for both images.

**Pull request closed without merging**
