### PR TITLE
fix: set the cap to 100

### PR DESCRIPTION
**Pull request by Rexogamer**
## Please make sure to check the following tasks before opening and submitting a PR

* [x] I understand and have followed the [contribution guide](https://github.com/revoltchat/revolt/discussions/282)
* [ ] I have tested my changes locally and they are working as intended
* [x] These changes do not have any notable side effects on other Revolt projects

dietz

### CODE REVIEW

**Comment by Rexogamer** [comment]
I have read the CLA Document and I hereby sign the CLA

**Comment by Rexogamer** [comment]
recheck

**Comment by DeMoN100** [comment]
Don't change the limit from 101 to 100. Increasing is always the way to go. Why not increase it to 1000?

**Comment by Rexogamer** [comment]
It is *one slot* and, again, is unintentional and unintuitive behaviour; please drop the stick

**Pull request merged**
