### PR TITLE
 removed check for bot account under group member fetch

### PR DESCRIPTION
**Pull request by toastxc**
## Please make sure to check the following tasks before opening and submitting a PR

* [x] I understand and have followed the [contribution guide](https://github.com/revoltchat/revolt/discussions/282)
* [x] I have tested my changes locally and they are working as intended
* [x] These changes do not have any notable side effects on other Revolt projects

### CODE REVIEW

**Comment by toastxc** [comment]
The output of this route is literally generic user data as shown in source, this information can be pulled by a bot by literally polling a user account
```rust
Result<Json<Vec<User>>>
```
I'm certain that this is not a security problem

**Comment by toastxc** [comment]
Unrelated: The name of this route doesn't seem right
Servers have members, and `Member` is a different data structure to what is return by this route.
Perhaps the route should be named `channels/group_member_fetch.rs` and `channels/group_member_fetch_all.rs` instead of `channels/members_fetch.rs`

**Review by Rexogamer — APPROVED** [review]
Bots can already fetch server members (a much more expensive operation, involving more data and usually more people than a group); LGTM although I'm curious if @insertish had a specific reason for this check

**Comment by insertish** [comment]
> Bots can already fetch server members (a much more expensive operation, involving more data and usually more people than a group); LGTM although I'm curious if @insertish had a specific reason for this check

no

**Review by insertish — APPROVED** [review]

**Pull request merged**
